### ISSUE TITLE
interp: escape sequences are ignored(?)

### ISSUE THREAD

**Issue by ebfe** [mvdan/sh#175]
```sh
x="1
2"
y="a\
b"
echo "$x"
echo "$y"
echo \$z
echo a\ b
```

bash
```
1
2
ab
$z
a b
```

gosh
```
1
2
a\
b
\$z
a\ b
```

**Comment by mvdan** [comment]
Where does the last line come from?

**Comment by ebfe** [comment]
Sorry, mixed up test files. Edited.

**Comment by mvdan** [comment]
I don't think the interpreter uses backslashes in any way at the moment. The syntax package does, but it has to keep them to not modify the plaintext program.

**Comment by mvdan** [comment]
I've fixed this in the way that I think it should work. Do let me know if I got it wrong, which is entirely possible. Your original script works now, though, so it seems to be okay at least for the simple cases.

**Comment by ebfe** [comment]
Looks good. Though this unearthed a segfault in gosh (previously raised a invalid variable name error):

```
i=1                                                     
eval declare X\${i}=foo                                 
echo $X1 
```

bash: `foo`
gosh
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x50939e]

goroutine 1 [running]:
mvdan.cc/sh/interp.(*Runner).assignValue(0xc4200a0000, 0xc4200743f0, 0x0, 0x0, 0xc420056260, 0x0)
	/go/src/mvdan.cc/sh/interp/interp.go:796 +0x3e
mvdan.cc/sh/interp.(*Runner).cmd(0xc4200a0000, 0x607820, 0xc420056240)
	/go/src/mvdan.cc/sh/interp/interp.go:1082 +0x1bd0
mvdan.cc/sh/interp.(*Runner).stmtSync(0xc4200a0000, 0xc42008d800)
	/go/src/mvdan.cc/sh/interp/interp.go:897 +0x2ee
mvdan.cc/sh/interp.(*Runner).stmt(0xc4200a0000, 0xc42008d800)
	/go/src/mvdan.cc/sh/interp/interp.go:782 +0xca
mvdan.cc/sh/interp.(*Runner).stmts(0xc4200a0000, 0xc420096800, 0x1, 0x4, 0x0, 0x0, 0x0)
	/go/src/mvdan.cc/sh/interp/interp.go:1122 +0x50
mvdan.cc/sh/interp.(*Runner).Run(0xc4200a0000, 0x606fe0, 0xc420056200, 0x0, 0x0)
	/go/src/mvdan.cc/sh/interp/interp.go:421 +0xe5
mvdan.cc/sh/interp.(*Runner).builtinCode(0x619a00, 0x1000200000004, 0xc420016200, 0x4, 0xc4200742e0, 0x2, 0x2, 0x0)
	/go/src/mvdan.cc/sh/interp/builtin.go:206 +0x690
mvdan.cc/sh/interp.(*Runner).call(0x619a00, 0x1000200000004, 0xc420016200, 0x4, 0xc4200742e0, 0x2, 0x2)
	/go/src/mvdan.cc/sh/interp/interp.go:1358 +0x2b0
mvdan.cc/sh/interp.(*Runner).cmd(0x619a00, 0x6076e0, 0xc42008aad0)
	/go/src/mvdan.cc/sh/interp/interp.go:951 +0x1466
mvdan.cc/sh/interp.(*Runner).stmtSync(0x619a00, 0xc42008c058)
	/go/src/mvdan.cc/sh/interp/interp.go:897 +0x2ee
mvdan.cc/sh/interp.(*Runner).stmt(0x619a00, 0xc42008c058)
	/go/src/mvdan.cc/sh/interp/interp.go:782 +0xca
mvdan.cc/sh/interp.(*Runner).stmts(0x619a00, 0xc420096000, 0x3, 0x4, 0x0, 0x0, 0x0)
	/go/src/mvdan.cc/sh/interp/interp.go:1122 +0x50
mvdan.cc/sh/interp.(*Runner).Run(0x619a00, 0x606fe0, 0xc420056140, 0x7ffdfab7d5c3, 0xd)
	/go/src/mvdan.cc/sh/interp/interp.go:421 +0xe5
main.run(0x606760, 0xc42000e028, 0x7ffdfab7d5c3, 0xd, 0x0, 0xc42003c2d0)
	/go/src/mvdan.cc/sh/cmd/gosh/main.go:73 +0xbf
main.runPath(0x7ffdfab7d5c3, 0xd, 0x0, 0x0)
	/go/src/mvdan.cc/sh/cmd/gosh/main.go:64 +0xb2
main.runAll(0xc420072058, 0x0)
	/go/src/mvdan.cc/sh/cmd/gosh/main.go:51 +0xcd
main.main()
	/go/src/mvdan.cc/sh/cmd/gosh/main.go:33 +0x2b
```

**Comment by ebfe** [comment]
Simpler testcase:

```
i=1
declare X${i}=foo
echo $X1
```

Should i open a separate issue?

**Comment by mvdan** [comment]
Thanks for reporting - this is another edge case I had not yet covered in the interpreter. The root of the problem is `declare $foo`, where the parameter needs to be expanded and re-parsed as an assignment. For example:

```
$ foo=a=b; declare $foo; echo $a
b
```

Obviously the static parser can't possibly deal with this, so it's up to the interpreter. It didn't, hence the boom. Committing a simple fix now.
