### ISSUE TITLE
interp: panic: variable name must not be empty

### ISSUE THREAD

**Issue by dmage** [mvdan/sh#236]
Steps to reproduce:
* Create x.sh:
```
# correct result: pwd
# incorrect result: date
echo "$\
(pwd ')">/dev/null
date
echo ')" #'>/dev/null
```
* gosh x.sh

Expected output:
```
/path/to/current/directory
```

Actual output:
```
panic: variable name must not be empty

goroutine 1 [running]:
mvdan.cc/sh/interp.(*Runner).lookupVar(0x61b0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/dmage/src/mvdan.cc/sh/interp/vars.go:137 +0x501
mvdan.cc/sh/interp.(*Runner).paramExp(0x61b0e0, 0xc4200a41e0, 0x0, 0x1)
	/home/dmage/src/mvdan.cc/sh/interp/param.go:85 +0x17f5
mvdan.cc/sh/interp.(*Runner).wordField(0x61b0e0, 0xc42000c0a0, 0x2, 0x2, 0x1, 0x1, 0xc42000c0a0, 0xc42000c200)
	/home/dmage/src/mvdan.cc/sh/interp/expand.go:271 +0x5ce
mvdan.cc/sh/interp.(*Runner).wordFields(0x61b0e0, 0xc420051420, 0x1, 0x1, 0xc420018128, 0x4, 0x0)
	/home/dmage/src/mvdan.cc/sh/interp/expand.go:357 +0xa04
mvdan.cc/sh/interp.(*Runner).Fields(0x61b0e0, 0xc4200b6ab0, 0x2, 0x4, 0x1, 0x44ef30, 0xc420071958)
	/home/dmage/src/mvdan.cc/sh/interp/expand.go:144 +0x6e6
mvdan.cc/sh/interp.(*Runner).cmd(0x61b0e0, 0x57ab40, 0xc4200b6a80)
	/home/dmage/src/mvdan.cc/sh/interp/interp.go:471 +0xeae
mvdan.cc/sh/interp.(*Runner).stmtSync(0x61b0e0, 0xc4200b8000)
	/home/dmage/src/mvdan.cc/sh/interp/interp.go:427 +0x324
mvdan.cc/sh/interp.(*Runner).stmt(0x61b0e0, 0xc4200b8000)
	/home/dmage/src/mvdan.cc/sh/interp/interp.go:408 +0xca
mvdan.cc/sh/interp.(*Runner).stmts(0x61b0e0, 0xc4200c2000, 0x3, 0x4, 0x0, 0x0, 0x0)
	/home/dmage/src/mvdan.cc/sh/interp/interp.go:685 +0x51
mvdan.cc/sh/interp.(*Runner).Run(0x61b0e0, 0x57a760, 0xc42002a180, 0x7ffd628290fb, 0xd)
	/home/dmage/src/mvdan.cc/sh/interp/interp.go:350 +0xe5
main.run(0x57a200, 0xc42000e030, 0x7ffd628290fb, 0xd, 0x0, 0xc4200b6000)
	/home/dmage/src/mvdan.cc/sh/cmd/gosh/main.go:73 +0xbf
main.runPath(0x7ffd628290fb, 0xd, 0x0, 0x0)
	/home/dmage/src/mvdan.cc/sh/cmd/gosh/main.go:64 +0xa8
main.runAll(0x405b5c, 0xc4200260b8)
	/home/dmage/src/mvdan.cc/sh/cmd/gosh/main.go:51 +0xbf
main.main()
	/home/dmage/src/mvdan.cc/sh/cmd/gosh/main.go:33 +0x2b
```

**Comment by mvdan** [comment]
That program you pasted is crafty :) I've fixed the crash you found, but I believe that the program still doesn't fully behave like Bash. That is, `$\\\n(` doesn't parse like `$(`. I'm not sure if there is a good solution to that for this parser, or if it's even worth bothering to fix it. At least it's not a crash, though.
