### ISSUE TITLE
Docker image panic on -f and -l

### ISSUE THREAD

**Issue by ArturKlauser** [mvdan/sh#466]
Shfmt panics in the docker image with `-f /` or `-l /`.

```
$ docker run --rm mvdan/shfmt:v3.0.0 -f /
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x54aee3]

goroutine 1 [running]:
main.walk.func1(0xc0000ec9c0, 0xc, 0x0, 0x0, 0x5d9740, 0xc000010930, 0x0, 0x0)
	/src/cmd/shfmt/main.go:211 +0x43
path/filepath.walk(0xc0000ec920, 0xa, 0x5dcc20, 0xc00010e270, 0xc00003de48, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:378 +0x20c
path/filepath.walk(0xc0000ec5f0, 0x7, 0x5dcc20, 0xc0000ef2b0, 0xc00003de48, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.walk(0xc0000ec3d0, 0x5, 0x5dcc20, 0xc0000ef1e0, 0xc00003de48, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.walk(0x7fff4939df88, 0x1, 0x5dcc20, 0xc00006f1e0, 0xc00003de48, 0x0, 0x5dcc20)
	/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.Walk(0x7fff4939df88, 0x1, 0xc00003de48, 0xc00006f110, 0x0)
	/usr/local/go/src/path/filepath/path.go:404 +0xff
main.walk(0x7fff4939df88, 0x1, 0xc00003df18)
	/src/cmd/shfmt/main.go:210 +0xf2
main.main1(0xc00006c058)
	/src/cmd/shfmt/main.go:173 +0x2fb
main.main()
	/src/cmd/shfmt/main.go:63 +0x22
```

This doesn't seem to be new to v3.0.0 either. When I try it on the oldest version on your docker hub I see the same:
```
$ docker run --rm mvdan/shfmt:v2.6.1 shfmt -f /
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x53b58f]
...
```

**Comment by mvdan** [comment]
Thanks, I can reproduce this. It looks like a minor mistake in the directory walking logic.
