### ISSUE TITLE
syntax: comment followed by a redirect causes a printer panic

### ISSUE THREAD

**Issue by LucasLarson** [mvdan/sh#659]
a minimal reproducible example is running shfmt against a file with the following contents:
```sh
#
>o
```

The file where I encountered the problem was 
https://github.com/coreutils/coreutils/blob/32ff1d1/tests/split/l-chunk.sh

If I undo coreutils/coreutils@056d6de and replace the instances of
```sh
> out
```
with
```sh
:> out
```
then no error occurs.

I’m on iTerm2 on macOS Big Sur 11.2 using shfmt 3.2.1 installed via Homebrew.

---
the output
```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x111cf29]

goroutine 1 [running]:
mvdan.cc/sh/v3/syntax.(*Printer).stmtList(0xc000140000, 0xc00015a000, 0x1, 0x4, 0x0, 0x0, 0x0)
	/private/tmp/shfmt-20201203-26187-10d7h0x/sh-3.2.1/syntax/printer.go:1235 +0xe9
mvdan.cc/sh/v3/syntax.(*Printer).Print(0xc000140000, 0x11d8880, 0x12c2dc0, 0x11d9680, 0xc000112780, 0xc000112780, 0x0)
	/private/tmp/shfmt-20201203-26187-10d7h0x/sh-3.2.1/syntax/printer.go:123 +0x53b
main.formatBytes(0xc000142000, 0x5, 0x600, 0x7ffeefbfceae, 0xa, 0x8000, 0x8000)
	/private/tmp/shfmt-20201203-26187-10d7h0x/sh-3.2.1/cmd/shfmt/main.go:349 +0x165
main.formatPath(0x7ffeefbfceae, 0xa, 0x11dbc00, 0x0, 0x0)
	/private/tmp/shfmt-20201203-26187-10d7h0x/sh-3.2.1/cmd/shfmt/main.go:326 +0x29f
main.main1(0xc000078058)
	/private/tmp/shfmt-20201203-26187-10d7h0x/sh-3.2.1/cmd/shfmt/main.go:202 +0x58d
main.main()
	/private/tmp/shfmt-20201203-26187-10d7h0x/sh-3.2.1/cmd/shfmt/main.go:72 +0x25
```

**Comment by mvdan** [comment]
Thank you for the detailed report!
