### ISSUE TITLE
Backslash line continuation without subsequent input causes panic

### ISSUE THREAD

**Issue by cortesi** [mvdan/sh#669]
Place the following in a file:

```
echo \
```

Make sure the file is NOT terminated by a newline after the backslash. If you're editing the file in vim, you may need to `:set nofixeol`, and you can verify that the last character in the file is a backslash using something like `hexdump -C`. 

Now execute the file with gosh:

`cat ./myfile | gosh`

On my system I see the following:

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
mvdan.cc/sh/v3/expand.(*Config).wordFields(0xc0000b0140, 0xc0000b8420, 0x1, 0x1, 0xc00001c150, 0x2, 0x0, 0x0, 0x0)
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/expand/expand.go:543 +0x129d
mvdan.cc/sh/v3/expand.Fields(0xc0000b0140, 0xc00000e090, 0x3, 0x3, 0xc00000e090, 0x415792, 0xc00000e090, 0xc0000baab0, 0x18)
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/expand/expand.go:384 +0x158
mvdan.cc/sh/v3/interp.(*Runner).fields(0xc0000b6000, 0xc00000e090, 0x3, 0x3, 0x3, 0x3, 0x0)
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/interp/runner.go:149 +0x5a
mvdan.cc/sh/v3/interp.(*Runner).cmd(0xc0000b6000, 0x5c1338, 0xc00001c0e0, 0x5c0c98, 0xc0000baa80)
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/interp/runner.go:332 +0x11aa
mvdan.cc/sh/v3/interp.(*Runner).stmtSync(0xc0000b6000, 0x5c1338, 0xc00001c0e0, 0xc0000bc000)
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/interp/runner.go:285 +0x312
mvdan.cc/sh/v3/interp.(*Runner).stmt(0xc0000b6000, 0x5c1338, 0xc00001c0e0, 0xc0000bc000)
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/interp/runner.go:266 +0x1e7
mvdan.cc/sh/v3/interp.(*Runner).stmts(0xc0000b6000, 0x5c1338, 0xc00001c0e0, 0xc0000c6000, 0x1, 0x4)
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/interp/runner.go:603 +0x57
mvdan.cc/sh/v3/interp.(*Runner).Run(0xc0000b6000, 0x5c1338, 0xc00001c0e0, 0x5bf9b0, 0xc00006e100, 0xc00006e100, 0x0)
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/interp/api.go:504 +0x2ef
main.run(0xc0000b6000, 0x5bf3d8, 0xc000010010, 0x0, 0x0, 0x0, 0xc00007c360)
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/cmd/gosh/main.go:64 +0xed
main.runAll(0xc0000221e0, 0xc000012220)
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/cmd/gosh/main.go:47 +0x1e5
main.main()
	/home/cortesi/go/pkg/mod/mvdan.cc/sh/v3@v3.2.2/cmd/gosh/main.go:24 +0x8a
```

This has caused a reported issue in modd (cortesi/modd#93).

**Comment by mvdan** [comment]
Thank you - I can reproduce:

```
$ echo -n '\' | gosh
panic: runtime error: index out of range [1] with length 1
```

Fix incoming. Please update to master for the time being, because I plan to do a v3.3 by the end of this month and I don't think a panic in the runner is urgent enough to warrant a v3.2.3 on its own.
