### ISSUE TITLE
interp: panic on set builtin with the end of options flag

### ISSUE THREAD

**Issue by ihar-orca** [mvdan/sh#816]
A full script:
```
#!/bin/bash

cat /etc/passwd | cut -f3 -d":" | sort -n | uniq -c | while read x; do
	[ -z "${x}" ] && break
	set - $x
	if [ $1 -gt 1 ]; then
		users=$(awk -F: '($3 == n) { print $1 }' n=$2 /etc/passwd | xargs)
		exit 1
	fi
done
```

Just a simple script to reproduce the issue:
```
#!/bin/bash
set - "test"
```

When I'm trying to run this script using the interp, I'm receiving a panic:
```
panic at runtime error: index out of range [1] with length 1
stacktrace from panic: 
goroutine 21 [running]:
runtime/debug.Stack()
        /Users/zettich/sdk/go1.17.6/go1.17.6/src/runtime/debug/stack.go:24 +0x7a
cli/pkg/cis.(*RunnerFactory).Run.func5()
        /Users/zettich/src/orca-cis/cli/pkg/cis/runner.go:127 +0xb4
panic({0x1596de0, 0xc00023a000})
        /Users/zettich/sdk/go1.17.6/go1.17.6/src/runtime/panic.go:1047 +0x262
mvdan.cc/sh/v3/interp.Params.func1(0xc000230000)
        /Users/zettich/go/pkg/mod/mvdan.cc/sh/v3@v3.4.3/interp/api.go:243 +0x80f
mvdan.cc/sh/v3/interp.(*Runner).builtinCode(0xc000230000, {0x177cf50, 0xc00012c008}, {0xc, 0x8001}, {0xc000200095, 0x3}, {0xc00020c160, 0x2, 0x2})
        /Users/zettich/go/pkg/mod/mvdan.cc/sh/v3@v3.4.3/interp/builtin.go:72 +0x550
mvdan.cc/sh/v3/interp.(*Runner).call(0xc000230000, {0x177cf50, 0xc00012c008}, {0xc, 0x8001}, {0xc00020c150, 0x3, 0x3})
        /Users/zettich/go/pkg/mod/mvdan.cc/sh/v3@v3.4.3/interp/runner.go:803 +0x527
mvdan.cc/sh/v3/interp.(*Runner).cmd(0xc000230000, {0x177cf50, 0xc00012c008}, {0x177bcc0, 0xc000218a80})
        /Users/zettich/go/pkg/mod/mvdan.cc/sh/v3@v3.4.3/interp/runner.go:362 +0x334c
mvdan.cc/sh/v3/interp.(*Runner).stmtSync(0xc000230000, {0x177cf50, 0xc00012c008}, 0xc00021c000)
        /Users/zettich/go/pkg/mod/mvdan.cc/sh/v3@v3.4.3/interp/runner.go:286 +0x3c5
mvdan.cc/sh/v3/interp.(*Runner).stmt(0xc000230000, {0x177cf50, 0xc00012c008}, 0xc00021c000)
        /Users/zettich/go/pkg/mod/mvdan.cc/sh/v3@v3.4.3/interp/runner.go:267 +0x1c9
mvdan.cc/sh/v3/interp.(*Runner).stmts(0xc000230000, {0x177cf50, 0xc00012c008}, {0xc000228000, 0x1, 0x4})
        /Users/zettich/go/pkg/mod/mvdan.cc/sh/v3@v3.4.3/interp/runner.go:656 +0x9a
mvdan.cc/sh/v3/interp.(*Runner).Run(0xc000230000, {0x177cf50, 0xc00012c008}, {0x177aba8, 0xc00021a000})
        /Users/zettich/go/pkg/mod/mvdan.cc/sh/v3@v3.4.3/interp/api.go:499 +0x2a5
cli/pkg/cis.(*RunnerFactory).Run(0xc00020a000, {0x15da35b, 0x9}, {0x7ff7bfefdf69, 0x1f}, {0x1f12a58, 0xc0001217c0})
        /Users/zettich/src/orca-cis/cli/pkg/cis/runner.go:132 +0x88d
```

It seems that interp does not process correctly the end of options flag:
```
- Signal the end of options, cause all remaining arguments to be assigned to the positional parameters. The -x and -v options are turned off. If there are no arguments, the positional parameters remain unchanged.
```

**Comment by mvdan** [comment]
Thanks, this sounds like a bug to fix, the kind where we're not checking for a length before using an index expression. Marking as a good first issue.
