### ISSUE TITLE
CalledProcessError from pre-commit

### ISSUE THREAD

**Issue by dpinol** [mvdan/sh#818]
With any version previous to 3.4.3, pre-commit automatically installs shfmt with this config:
```
      - id: shfmt
        name: shfmt
        language: golang
        require_serial: true
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.4.3]
        entry: shfmt
        args: ["-l", "-w", "-i", "4", "-ci", "bin"]
        types: [shell]
```

With 3.4.3, I get this error:
```
pre-commit run --all 
[INFO] Installing environment for local.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/dani/.local/bin/go', 'install', './...')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    go: no module declaration in go.mod. To specify the module path:
        go mod edit -module=example.com/mod
    
Check the log at /home/dani/.cache/pre-commit/pre-commit.log
```

In the log I get:

```
### version information

pre-commit version: 2.17.0
git --version: git version 2.32.0
sys.version:
    3.9.10 (main, Jan 24 2022, 12:49:37) 
    [GCC 11.2.0]
sys.executable: /home/dani/.pyenv/versions/3.9.10/bin/python
os.name: posix
sys.platform: linux

### error information

An unexpected error has occurred: CalledProcessError: command: ('/home/dani/.local/bin/go', 'install', './...')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    go: no module declaration in go.mod. To specify the module path:
    	go mod edit -module=example.com/mod
    

Traceback (most recent call last):
  File "/home/dani/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pre_commit/error_handler.py", line 70, in error_handler
    yield
  File "/home/dani/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pre_commit/main.py", line 396, in main
    return run(args.config, store, args)
  File "/home/dani/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pre_commit/commands/run.py", line 416, in run
    install_hook_envs(to_install, store)
  File "/home/dani/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pre_commit/repository.py", line 224, in install_hook_envs
    _hook_install(hook)
  File "/home/dani/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pre_commit/repository.py", line 82, in _hook_install
    lang.install_environment(
  File "/home/dani/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pre_commit/languages/golang.py", line 82, in install_environment
    cmd_output_b('go', 'install', './...', cwd=repo_src_dir, env=env)
  File "/home/dani/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pre_commit/util.py", line 154, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/home/dani/.local/bin/go', 'install', './...')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    go: no module declaration in go.mod. To specify the module path:
    	go mod edit -module=example.com/mod
```

**Comment by mvdan** [comment]
What go version are you on? Make sure it's at least Go 1.16.

I haven't touched my go.mod file in v3.4.3, so if anything this sounds like a bug in pre-commit, or something that has gone wrong with your setup.

**Comment by dpinol** [comment]
yes, I had switched the pre-commit version.
After clearing up, everything worked fine.

thanks
